- name: Install libreoffice
  become: yes
  pacman: 
    name: libreoffice

- name: Install firefox
  become: yes
  pacman: 
    name: firefox

- name: Install chrome
  yay: 
    name: google-chrome

- name: Install sublime text
  yay: 
    name: sublime-text-dev

- name: Install vscode
  yay: 
    name: visual-studio-code-bin

- name: Install spotify
  yay: 
    name: spotify

- name: Install slack
  yay: 
    name: slack-desktop

- name: Install skype
  yay: 
    name: skypeforlinux-preview-bin

- name: Install whatsapp
  yay: 
    name: whatsapp-nativefier

- name: Install postman
  yay: 
    name: postman-bin

- name: Ensure postman config dir exists
  file: 
    path: ~/.config/Postman/Postman_Config/0
    state: directory

- name: Install typora
  yay: 
    name: typora

- name: Install docker and docker-compose
  become: yes
  pacman: 
    name: 
      - docker
      - docker-compose

- name: Enable and start docker daemon
  become: yes
  systemd: 
    name: docker
    enabled: yes
    state: started

- name: Add user to docker group
  become: yes
  user:
    name: "{{ ansible_user }}"
    group: docker
    append: yes

- name: Install aws-cli
  become: yes
  pacman: 
    name: aws-cli

- name: Install terraform
  become: yes
  pacman: 
    name: terraform

- name: Install openjdk 8
  become: yes
  pacman: 
    name: jdk8-openjdk

- name: Install groovy
  become: yes
  pacman:
    name: groovy

- name: Install golang
  become: yes
  pacman: 
    name: go

- name: Install nodejs, npm and yarn
  become: yes
  pacman:
    name: 
      - nodejs
      - npm
      - yarn

- name: Install intellij ultimate
  yay: 
    name: intellij-idea-ultimate-edition

- name: Install goland
  yay: 
    name: goland

- name: Install datagrip
  yay: 
    name: datagrip
