- name: Install Xorg and tools
  become: yes
  pacman:
    name:
      - xorg-server
      - xorg-xinit
      - xorg-xfd
      - xorg-xprop
      - xorg-xkill
      - xautomation
      - xbindkeys

- name: Install i3, i3status and i3lock
  become: yes
  pacman:
    name:
      - i3-gaps
      - i3status
      - i3lock

- name: Ensure i3 config dir exists
  file:
    path: ~/.config/i3
    state: directory

- name: Ensure i3status config dir exists
  file:
    path: ~/.config/i3status
    state: directory

- name: Install polybar
  yay:
    name: polybar

- name: Ensure polybar config dir exists
  file:
    path: ~/.config/polybar
    state: directory

- name: Install rofi
  become: yes
  pacman:
    name: rofi

- name: Install rofi-calc
  yay:
    name: rofi-calc

- name: Ensure rofi config dir exists
  file:
    path: ~/.config/rofi
    state: directory

- name: Install termite
  become: yes
  pacman:
    name: termite

- name: Install alacritty
  become: yes
  pacman:
    name: alacritty

- name: Ensure termite config dir exists
  file:
    path: ~/.config/termite
    state: directory

- name: Ensure alacritty config dir exists
  file:
    path: ~/.config/alacritty
    state: directory

- name: Install pcman
  become: yes
  pacman:
    name: pcmanfm

- name: Install screen utilities
  become: yes
  pacman:
    name:
      - scrot
      - feh
      - lxappearance
      - lxrandr

- name: Install autorandr
  yay:
    name: autorandr

- name: Install arc-gtk-theme
  become: yes
  pacman:
    name:
      - arc-gtk-theme

- name: Ensure gtk-3.0 config dir exists
  file:
    path: ~/.config/gtk-3.0
    state: directory
