- name: Link .dotfiles
  file: src={{ item.src }} dest={{ item.dest }} state=link
  with_items:
    - { src: "~/.dotfiles/.gitconfig", dest: "~/.gitconfig" }
    - { src: "~/.dotfiles/.xinitrc", dest: "~/.xinitrc" }
    - { src: "~/.dotfiles/.zshrc", dest: "~/.zshrc" }
    - { src: "~/.dotfiles/.config/gtk-3.0/settings.ini", dest: "~/.config/gtk-3.0/settings.ini" }
    - { src: "~/.dotfiles/.config/i3/config", dest: "~/.config/i3/config" }
    - { src: "~/.dotfiles/.config/i3/arch.png", dest: "~/.config/i3/arch.png" }
    - { src: "~/.dotfiles/.config/polybar/config", dest: "~/.config/polybar/config" }
    - { src: "~/.dotfiles/.config/polybar/launch.sh", dest: "~/.config/polybar/launch.sh" }
    - { src: "~/.dotfiles/.config/polybar/bluetooth.sh", dest: "~/.config/polybar/bluetooth.sh" }
    - { src: "~/.dotfiles/.config/polybar/playerctl.sh", dest: "~/.config/polybar/playerctl.sh" }
    - { src: "~/.dotfiles/.config/Postman/Postman_Config/0/userconfigs.json", dest: "~/.config/Postman/Postman_Config/0/userconfigs.json" }
    - { src: "~/.dotfiles/.config/rofi/config", dest: "~/.config/rofi/config" }
    - { src: "~/.dotfiles/.config/rofi/glue_pro_blue.rasi", dest: "~/.config/rofi/glue_pro_blue.rasi" }
    - { src: "~/.dotfiles/.config/termite/config", dest: "~/.config/termite/config" }
