- name: Install openjdk 8
  become: yes
  pacman:
    name: jdk8-openjdk

- name: Install openjdk 11
  become: yes
  pacman:
    name: jdk11-openjdk

- name: Check default java environment
  become: yes
  shell: archlinux-java get
  register: default_java
  changed_when: False

- name: Set openjdk-11 as default java environment
  become: yes
  shell: archlinux-java set java-11-openjdk
  when: default_java.stdout != 'java-11-openjdk'

- name: Install groovy
  become: yes
  pacman:
    name: groovy

- name: Install maven
  become: yes
  pacman:
    name: maven

- name: Install gradle
  become: yes
  pacman:
    name: gradle

- name: Install go
  become: yes
  pacman:
    name: go

- name: Install python
  become: yes
  pacman:
    name: python

- name: Install ruby
  become: yes
  pacman:
    name: ruby

- name: Install nodejs, npm and yarn
  become: yes
  pacman:
    name:
      - nodejs
      - npm
      - yarn

- name: Install docker and docker-compose
  become: yes
  pacman:
    name:
      - docker
      - docker-compose

- name: Enable and start docker daemon
  become: yes
  systemd:
    name: docker
    enabled: yes
    state: started

- name: Add user to docker group
  become: yes
  user:
    name: "{{ ansible_user }}"
    group: docker
    append: yes

- name: Install virtualbox
  become: yes
  pacman:
    name:
      - virtualbox
      - virtualbox-host-modules-arch

- name: Load virtualbox kernel modules
  become: yes
  modprobe:
    name: vboxdrv
    state: present

- name: Install minikube
  become: yes
  pacman:
    name: minikube

- name: Install kubectl
  become: yes
  pacman:
    name: kubectl

- name: Install aws-cli
  become: yes
  pacman:
    name: aws-cli

- name: Install terraform
  become: yes
  pacman:
    name: terraform

- name: Install wrk
  yay:
    name: wrk

- name: Install apache-tools
  yay:
    name: apache-tools

- name: Install sublime text
  yay:
    name: sublime-text-dev

- name: Install vscode
  yay:
    name: visual-studio-code-bin

- name: Install postman
  yay:
    name: postman-bin

- name: Ensure postman config dir exists
  file:
    path: ~/.config/Postman/Postman_Config/0
    state: directory

- name: Install jetbrains toolbox
  yay:
    name: jetbrains-toolbox

