- name: Install pacman tools
  become: yes
  pacman:
    name:
      - reflector
      - pacman-contrib

- name: Optimize pacman mirrors
  become: yes
  shell: reflector --protocol https --sort rate --save /etc/pacman.d/mirrorlist
  when: false

- name: Install connman
  become: yes
  pacman: 
    name: connman

- name: Install connman-ncurses
  packer: 
    name: connman-ncurses

- name: Ensure connman config dir exists
  become: yes
  file: 
    path: /etc/connman 
    state: directory

- name: Copy connman config
  become: yes
  copy: 
    src: ../files/connman.conf 
    dest: /etc/connman/main.conf

- name: Enable and start connman
  become: yes
  systemd: 
    name: connman 
    enabled: yes 
    state: started

- name: Remove network tools from base
  become: yes
  pacman: 
    name: 
      - netctl
      - dhcpcd
    state: absent

- name: Install audio tools
  become: yes
  pacman:
    name:
      - alsa-utils
      - pulseaudio
      - pulseaudio-alsa
      - pavucontrol
      - playerctl

- name: Install bluetooth tools
  become: yes
  pacman:
    name:
      - bluez
      - bluez-utils
      - pulseaudio-bluetooth

- name: Enable bluetooth service
  become: yes
  systemd: 
    name: bluetooth
    enabled: yes
    state: started

- name: Install ZSH
  become: yes
  pacman: 
    name: zsh

- name: Set ZSH as user's shell
  become: yes
  shell: chsh -s /bin/zsh rodolpho

- name: Install oh-my-zsh
  shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"

- name: Install lambda-mod ZSH theme
  get_url: 
    url: https://raw.githubusercontent.com/halfo/lambda-mod-zsh-theme/master/lambda-mod.zsh-theme
    dest: ~/.oh-my-zsh/themes/lambda-mod.zsh-theme

- name: Install termite
  become: yes
  pacman:
    name: termite

- name: Install core packages
  become: yes
  pacman:
    name:
      - git
      - openssh
      - openvpn
      - curl
      - wget
      - zip
      - unzip
      - jq
      - xclip
      - sl

- name: Install pacman fonts
  become: yes
  pacman:
    name:
      - ttf-dejavu
      - ttf-fira-mono
      - ttf-font-awesome
      - noto-fonts
      - noto-fonts-emoji
      - noto-fonts-extra
      - adobe-source-code-pro-fonts

- name: Install aur fonts
  packer: 
    name: nerd-fonts-complete

- name: Install Xorg and tools
  become: yes
  pacman:
    name:
      - xorg-server
      - xorg-xinit

- name: Install i3
  become: yes
  pacman: 
    name: i3-wm

- name: Install polybar
  packer: 
    name: polybar

- name: Install rofi
  become: yes
  pacman:
    name: rofi

- name: Install rofi-calc
  packer:
    name: rofi-calc

- name: Install pcman
  become: yes
  pacman: 
    name: pcmanfm

- name: Install screen utilities
  become: yes
  pacman:
    name:
      - i3lock
      - scrot
      - feh
      - light
      - lxappearance
      - lxrandr