- name: Playbook to install dotfiles (https://github.com/rodolphocouto/dotfiles)
  hosts: localhost
  connection: local
  tasks:
    - include: tasks/system.yml
    - include: tasks/applications.yml
    - include: tasks/dotfiles.yml